//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion_recurso
    {
        public int id { get; set; }
        public int mision_id { get; set; }
        public int recurso_id { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<System.DateTime> fecha_liberacion { get; set; }
        public bool activa { get; set; }
    
        public virtual mision mision { get; set; }
        public virtual recurso_exploracion recurso_exploracion { get; set; }
    }
}
