//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class mision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mision()
        {
            this.asignacion_recurso = new HashSet<asignacion_recurso>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin_estimada { get; set; }
        public byte prioridad { get; set; }
        public byte estado { get; set; }
        public int responsable_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_recurso> asignacion_recurso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
