//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class orbita_controlEntities : DbContext
    {
        public orbita_controlEntities()
            : base("name=orbita_controlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignacion_recurso> asignacion_recurso { get; set; }
        public virtual DbSet<dron> dron { get; set; }
        public virtual DbSet<estacion_sensores> estacion_sensores { get; set; }
        public virtual DbSet<mision> mision { get; set; }
        public virtual DbSet<recurso_exploracion> recurso_exploracion { get; set; }
        public virtual DbSet<rover_terrestre> rover_terrestre { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<vw_asignaciones_activas> vw_asignaciones_activas { get; set; }
        public virtual DbSet<vw_recurso_detalle> vw_recurso_detalle { get; set; }
    }
}
