//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurso_exploracion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recurso_exploracion()
        {
            this.asignacion_recurso = new HashSet<asignacion_recurso>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string modelo { get; set; }
        public string tipo { get; set; }
        public byte estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignacion_recurso> asignacion_recurso { get; set; }
        public virtual dron dron { get; set; }
        public virtual estacion_sensores estacion_sensores { get; set; }
        public virtual rover_terrestre rover_terrestre { get; set; }
    }
}
