//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class rover_terrestre
    {
        public int recurso_id { get; set; }
        public decimal autonomia { get; set; }
        public decimal capacidad_carga { get; set; }
        public decimal costo_por_kilometro { get; set; }
    
        public virtual recurso_exploracion recurso_exploracion { get; set; }
    }
}
