//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_asignaciones_activas
    {
        public int asignacion_id { get; set; }
        public int mision_id { get; set; }
        public string codigo_mision { get; set; }
        public string nombre_mision { get; set; }
        public int recurso_id { get; set; }
        public string codigo_recurso { get; set; }
        public string modelo_recurso { get; set; }
        public string tipo_recurso { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
    }
}
