//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORBITAL.Datos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_recurso_detalle
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string modelo { get; set; }
        public string tipo { get; set; }
        public byte estado { get; set; }
        public Nullable<decimal> autonomia_vuelo { get; set; }
        public Nullable<decimal> alcance { get; set; }
        public Nullable<decimal> costo_por_hora { get; set; }
        public Nullable<decimal> autonomia_rover { get; set; }
        public Nullable<decimal> capacidad_carga { get; set; }
        public Nullable<decimal> costo_por_kilometro { get; set; }
        public Nullable<int> cantidad_sensores { get; set; }
        public Nullable<decimal> consumo_energetico { get; set; }
        public Nullable<decimal> costo_diario { get; set; }
    }
}
